/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { BTCUtils } from "./BTCUtils";

export class BTCUtilsFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<BTCUtils> {
    return super.deploy(overrides) as Promise<BTCUtils>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): BTCUtils {
    return super.attach(address) as BTCUtils;
  }
  connect(signer: Signer): BTCUtilsFactory {
    return super.connect(signer) as BTCUtilsFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BTCUtils {
    return new Contract(address, _abi, signerOrProvider) as BTCUtils;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "DIFF1_TARGET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "ERR_BAD_ARG",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "RETARGET_PERIOD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "RETARGET_PERIOD_BLOCKS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x60d1610025600b82828239805160001a60731461001857fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060515760003560e01c8063056e04ec1460565780638cc7156914606e5780638db69e60146074578063d4258ca714607a575b600080fd5b605c6080565b60408051918252519081900360200190f35b605c6087565b605c608d565b605c6093565b6212750081565b6107e081565b60001981565b61ffff60d01b8156fea265627a7a723158208cbb2c62661f0bb493542d25ad1b28dc6e74cfc14d89ada11128a4504a47a43564736f6c634300050f0032";
