/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { BTCUtils } from "./BTCUtils";

export class BTCUtilsFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<BTCUtils> {
    return super.deploy(overrides) as Promise<BTCUtils>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): BTCUtils {
    return super.attach(address) as BTCUtils;
  }
  connect(signer: Signer): BTCUtilsFactory {
    return super.connect(signer) as BTCUtilsFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BTCUtils {
    return new Contract(address, _abi, signerOrProvider) as BTCUtils;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "DIFF1_TARGET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "ERR_BAD_ARG",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "RETARGET_PERIOD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "RETARGET_PERIOD_BLOCKS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x610159610026600b82828239805160001a60731461001957fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100565760003560e01c8063056e04ec1461005b5780638cc71569146100795780638db69e6014610097578063d4258ca7146100b5575b600080fd5b6100636100d3565b6040518082815260200191505060405180910390f35b6100816100da565b6040518082815260200191505060405180910390f35b61009f6100e0565b6040518082815260200191505060405180910390f35b6100bd610104565b6040518082815260200191505060405180910390f35b6212750081565b6107e081565b7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff81565b7bffff00000000000000000000000000000000000000000000000000008156fea265627a7a72315820cc7e09c819f2603f74598dad75b3d0aeae9d77d9b6e2784764c722d77f2fe23964736f6c634300050f0032";
